/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package vista;

/**
 *
 * @author Geirel
 */
import controlador.KeyboardController;
import vista.GamePanel;
import javax.swing.*;
import java.awt.*;

public class GameFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameFrame.class.getName());
    /**
     * Creates new form GameFrame
     */
    private TopPanel topPanel;
    private GamePanel gamePanel;
    private BottomPanel bottomPanel;
    
    public GameFrame(String nombre1,String nombre2) {
        initComponents();
        
        topPanel = new TopPanel();
        gamePanel = new GamePanel(topPanel,nombre1,nombre2);
        bottomPanel = new BottomPanel(gamePanel);
        // Agregar al frame
        //add(topPanel, BorderLayout.NORTH);   // 🔑 nombres y puntos arriba
        //add(gamePanel, BorderLayout.CENTER);

        topContainer.setLayout(new java.awt.BorderLayout());
        gameContainer.setLayout(new java.awt.BorderLayout());
        bottomContainer.setLayout(new java.awt.BorderLayout());

        topContainer.add(topPanel);
        gameContainer.add(gamePanel);
        bottomContainer.add(bottomPanel);
        
        topPanel.setPreferredSize(new java.awt.Dimension(900, 70));
    gamePanel.setPreferredSize(new java.awt.Dimension(900, 470));
    bottomPanel.setPreferredSize(new java.awt.Dimension(900, 60));

        KeyboardController keyboardController = new KeyboardController(gamePanel);

        gamePanel.addKeyListener(keyboardController);

        gamePanel.setFocusable(true);
        gamePanel.requestFocusInWindow();

        setLocationRelativeTo(null);
    }
    
    
    public TopPanel getTopPanel() {
    return topPanel;
    }

    public GamePanel getGamePanel() {
        return gamePanel;
    }

    public BottomPanel getBottomPanel() {
        return bottomPanel;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topContainer = new javax.swing.JPanel();
        bottomContainer = new javax.swing.JPanel();
        gameContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ping Pong Multihilo Extreme");
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        topContainer.setForeground(java.awt.Color.yellow);
        topContainer.setPreferredSize(new java.awt.Dimension(900, 70));

        javax.swing.GroupLayout topContainerLayout = new javax.swing.GroupLayout(topContainer);
        topContainer.setLayout(topContainerLayout);
        topContainerLayout.setHorizontalGroup(
            topContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        topContainerLayout.setVerticalGroup(
            topContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(topContainer, java.awt.BorderLayout.PAGE_START);

        bottomContainer.setForeground(java.awt.Color.gray);
        bottomContainer.setMinimumSize(new java.awt.Dimension(900, 60));

        javax.swing.GroupLayout bottomContainerLayout = new javax.swing.GroupLayout(bottomContainer);
        bottomContainer.setLayout(bottomContainerLayout);
        bottomContainerLayout.setHorizontalGroup(
            bottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        bottomContainerLayout.setVerticalGroup(
            bottomContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(bottomContainer, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout gameContainerLayout = new javax.swing.GroupLayout(gameContainer);
        gameContainer.setLayout(gameContainerLayout);
        gameContainerLayout.setHorizontalGroup(
            gameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        gameContainerLayout.setVerticalGroup(
            gameContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        getContentPane().add(gameContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameFrame("Jugador 1","Jugador 2").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomContainer;
    private javax.swing.JPanel gameContainer;
    private javax.swing.JPanel topContainer;
    // End of variables declaration//GEN-END:variables
}
