/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import modelo.Paleta;
import java.awt.Graphics;
import modelo.Bola;
import javax.swing.Timer;
import java.util.ArrayList;
/**
 *
 * @author Geirel
 */


public class GamePanel extends javax.swing.JPanel {

    private Paleta paletaIzquierda;
    private Paleta paletaDerecha;
    private ArrayList<Bola> bolas;
    private Timer timer;
    /**
     * Creates new form GamePanelñ
     */
    public GamePanel() {

    initComponents();

    setPreferredSize(new java.awt.Dimension(900,470));
    setSize(900,470);


    paletaIzquierda = new Paleta(20,180);
    paletaDerecha = new Paleta(865,180);


    bolas = new ArrayList<>();


    Bola bola1 = new Bola(440,225);

    Bola bola2 = new Bola(400,150);

    bola2.configurarJuego(
    paletaIzquierda,
    paletaDerecha,
    900,
    420
    );


    Bola bola3 = new Bola(500,300);

    bola3.configurarJuego(
    paletaIzquierda,
    paletaDerecha,
    900,
    420
    );

    bola1.configurarJuego(
        paletaIzquierda,
        paletaDerecha,
        900,
        420
    );


    bolas.add(bola1);
    bolas.add(bola2);
    bolas.add(bola3);

    bola1.start();
    bola2.start();
    bola3.start();


    timer = new Timer(15, e -> {

        repaint();

    });


    timer.start();


    setFocusable(true);

}
    
   @Override
protected void paintComponent(Graphics g) {

    super.paintComponent(g);


    paletaIzquierda.dibujar(g);
    paletaDerecha.dibujar(g);


    for(Bola bola : bolas){

        bola.dibujar(g);

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(java.awt.Color.black);
        setPreferredSize(new java.awt.Dimension(900, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public Paleta getPaletaIzquierda(){
        return paletaIzquierda;
    }
    
    public Paleta getPletaDerecha(){
        return paletaDerecha;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
  
    


