/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import modelo.Paleta;
import java.awt.Graphics;
import modelo.Bola;
import javax.swing.Timer;
/**
 *
 * @author Geirel
 */


public class GamePanel extends javax.swing.JPanel {

    private Paleta paletaIzquierda;
    private Paleta paletaDerecha;
    private Bola bola;
    private Timer timer;
    /**
     * Creates new form GamePanelñ
     */
    public GamePanel() {

    initComponents();

    setPreferredSize(new java.awt.Dimension(900,470));
    setSize(900,470);

    paletaIzquierda = new Paleta(20,180);
    paletaDerecha = new Paleta(865,180);
    bola = new Bola(440,225);


    timer = new Timer(15, e -> {

        bola.mover(
            paletaIzquierda,
            paletaDerecha,
            900,
            420
        );

        repaint();

    });


    timer.start();

    setFocusable(true);
}    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        
        paletaIzquierda.dibujar(g);
        paletaDerecha.dibujar(g);
        bola.dibujar(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(java.awt.Color.black);
        setPreferredSize(new java.awt.Dimension(900, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public Paleta getPaletaIzquierda(){
        return paletaIzquierda;
    }
    
    public Paleta getPletaDerecha(){
        return paletaDerecha;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

   @Override
   public void addNotify(){

    super.addNotify();

    timer.start();

 } 
}    
    
    


