/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import javax.swing.JLabel;
/**
 *
 * @author Geirel
 */
public class TopPanel extends javax.swing.JPanel {
    
    private JLabel labelJugador1;
    private JLabel labelJugador2;
    private int puntos1 =0;
    
    /**
     * Creates new form TopPanel
     */
    public TopPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJugador1 = new javax.swing.JLabel();
        lblPuntos1 = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblPuntos2 = new javax.swing.JLabel();
        lblJugadore2 = new javax.swing.JLabel();

        setBackground(java.awt.Color.darkGray);
        setForeground(java.awt.Color.white);
        setToolTipText("");

        lblJugador1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblJugador1.setForeground(java.awt.Color.white);
        lblJugador1.setText("Jugador 1");

        lblPuntos1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblPuntos1.setForeground(java.awt.Color.white);
        lblPuntos1.setText("Puntos: 0");

        lblTiempo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTiempo.setForeground(java.awt.Color.yellow);
        lblTiempo.setText("Tiempo: 60");

        lblPuntos2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblPuntos2.setForeground(java.awt.Color.white);
        lblPuntos2.setText("Puntos: 0");

        lblJugadore2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblJugadore2.setForeground(java.awt.Color.white);
        lblJugadore2.setText("Jugador 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblJugador1)
                .addGap(85, 85, 85)
                .addComponent(lblPuntos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(lblTiempo)
                .addGap(97, 97, 97)
                .addComponent(lblJugadore2)
                .addGap(116, 116, 116)
                .addComponent(lblPuntos2)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugador1)
                    .addComponent(lblPuntos1)
                    .addComponent(lblTiempo)
                    .addComponent(lblJugadore2)
                    .addComponent(lblPuntos2))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

public void actualizarJugador1(String nombre){
    
    lblJugador1.setText(nombre);
    repaint();
}
public void actualizarJugador2(String nombre) {
    lblJugadore2.setText(nombre);
    repaint();
}
public void actualizarPuntos(int puntos){
    lblPuntos1.setText("Puntos: " + puntos);
    this.revalidate();
    this.repaint();
}
public void actualizarPuntos2(int  puntos){
    lblPuntos2.setText("Puntos: " + puntos);
    this.revalidate();
    this.repaint();
}
public void actualizarTiempo(int tiempo){
    lblTiempo.setText("Tiempo: " + tiempo);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugadore2;
    private javax.swing.JLabel lblPuntos1;
    private javax.swing.JLabel lblPuntos2;
    private javax.swing.JLabel lblTiempo;
    // End of variables declaration//GEN-END:variables
}
